[RHTAPBUGS-595]add deletecollection permission to controllers
redhat-appstudio/application-service pull request #380
Opened 2023-08-14 21:14 UTC by yangcao77

### What does this PR do?:

This PR adds deletecollection verb to controllers

### Which issue(s)/story(ies) does this PR fixes:

https://issues.redhat.com/browse/RHTAPBUGS-595

### PR acceptance criteria:

- [ ] Unit/Functional tests

  

- [ ] Documentation 

   

- [ ] Client Impact

  

### How to test changes / Special notes to the reviewer:

2023-08-14 23:08 UTC, maysunfaisal commented on controllers/applicationsnapshotenvironmentbinding_controller.go
> +//+kubebuilder:rbac:groups=appstudio.redhat.com,resources=snapshotenvironmentbindings,verbs=get;list;watch;create;update;patch;delete;deletecollection
do we need to update config/rbac?

2023-08-15 00:22 UTC, yangcao77 commented on controllers/applicationsnapshotenvironmentbinding_controller.go
> +//+kubebuilder:rbac:groups=appstudio.redhat.com,resources=snapshotenvironmentbindings,verbs=get;list;watch;create;update;patch;delete;deletecollection
oops. updated

2023-08-15 13:46 UTC, johnmcollier requested changes

2023-08-15 13:46 UTC, johnmcollier commented on controllers/application_controller.go
> +//+kubebuilder:rbac:groups=appstudio.redhat.com,resources=applications,verbs=get;list;watch;create;update;patch;delete;deletecollection
HAS itself doesn’t need the deletecollection verb, just the RHTAP users, so we don’t need to add it to HAS here

2023-08-15 17:38 UTC, closed without merging