[WIP] Allow the overriding of the default build bundle by using a configmap
redhat-appstudio/application-service pull request #74
Opened 2022-03-10 18:01 UTC by brunoapimentel

We need to [implement the concept of organizations](https://issues.redhat.com/browse/PLNSRVCE-56) and allow the sharing of assets in a non-KCP world. 

This PR is a first step in that direction, providing a simple mechanism to define a configmap that'll allow HAS to use a specific Tekton bundle instead of the default one.

Here's a sample configmap, which should be placed in the same namespace where the HAS application/component objects will be created.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipelines-defaults
data:
  default_build_bundle: "quay.io/user/custombundle:version" 
```
In case this configmap is not available, HAS will try to search for one with the same name at the `build-templates` namespace, which is currently defined as default by the infra-deployments [configuration](https://github.com/redhat-appstudio/infra-deployments/blob/1c6328ee54c4ccde2d2bc58bd845d3eb024ae0f3/components/build/kustomization.yaml#L11). 

If no configmap is found, it will resort to the one that's currently [hardcoded](https://github.com/brunoapimentel/application-service/blob/96308c90f86acc7b6993a4deb7cf5da17835a3e1/gitops/generate_build.go#L42).

2022-03-10 19:05 UTC, johnmcollier commented
/ok-to-test

2022-03-11 15:35 UTC, brunoapimentel commented on controllers/component_controller_test.go
> -				fmt.Println(createdHasComp.ResourceVersion)
Deleted this because it was priting undesired output to during the tests' run, I figured it was left here by accident.

2022-03-14 16:45 UTC, brunoapimentel commented
/retest

2022-03-16 20:29 UTC, johnmcollier requested changes

2022-03-16 20:38 UTC, brunoapimentel commented on controllers/component_controller_test.go
> +func createComponent(name string, namespace string, application string, componentName string, gitUrl string) types.NamespacedName {
If you think this can be reused for other tests, then I'd say it's worth it.

2022-03-17 13:11 UTC, johnmcollier commented on controllers/component_controller_test.go
> +func createComponent(name string, namespace string, application string, componentName string, gitUrl string) types.NamespacedName {
Yeah, I think we could use this to refactor our tests a bit

2022-03-17 18:57 UTC, brunoapimentel commented on controllers/component_controller.go
> +func (r *ComponentReconciler) resolveBuildBundle(ctx context.Context, component appstudiov1alpha1.Component) string {
Well, the best approach I could think of is returning both possible errors (component namespace level and default namespace level) from that function:

```
// bad approach, would hide first error
component's namespace -> throws error -> default namespace -> succeeds, returns no error

// chosen approach, would hide first error
component's namespace -> throws error -> default namespace -> succeeds, returns bundle and first error
component's namespace -> throws error -> default namespace -> throws error -> returns both errors
```

Wdyt?

2022-03-17 18:58 UTC, brunoapimentel commented on controllers/component_controller.go
> +func (r *ComponentReconciler) resolveBuildBundle(ctx context.Context, component appstudiov1alpha1.Component) string {
Also, I did not put the errors in the component's status now. Do you think we should go for that approach straight away?

2022-03-21 16:03 UTC, johnmcollier commented on controllers/component_controller.go
> +func (r *ComponentReconciler) resolveBuildBundle(ctx context.Context, component appstudiov1alpha1.Component) string {
Yeah, we can hold on putting the component's status for now I suppose.

2022-03-21 16:04 UTC, johnmcollier commented on controllers/component_controller_test.go
> +func createComponent(name string, namespace string, application string, componentName string, gitUrl string) types.NamespacedName {
Yeah, that would make sense, but we can leave as-is for now.

2022-03-22 20:38 UTC, johnmcollier approved these changes

2022-04-04 19:39 UTC, johnmcollier commented
@brunoapimentel can you rebase?

2022-04-04 20:02 UTC, brunoapimentel commented
> @brunoapimentel can you rebase?

Sorry, I should've already closed this PR. We'll be moving this implementation to the new [build-service](https://github.com/redhat-appstudio/build-service) operator.

2022-04-04 20:02 UTC, closed without merging